openapi: 3.0.0
info:
  title: Заказ
  version: 0.0.1
servers:
  - url: http://localhost:8080/api/v1/
    description: Local server
paths:
  /clouds:
    get:
      summary: Метод получения списка ресурсов и облака
      tags:
        - Clouds
      operationId: getAllClouds
      responses:
        "200":
          description: Успешный ответ со списокм
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Clouds"
        "default":
          description: Успешный ответ со списокм
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Метод получения списка ресурсов и облака
      tags:
        - Clouds
      operationId: creatCloud
      requestBody:
        content:
          adplication/json:
            schema:
              $ref: "#/components/schemas/Clouds"
      responses:
        "200":
          description: Успешный ответ со списокм
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Clouds"  
        "default":
          description: other
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Error"
  /louds/{cloud_id}:
    get:
      summary: Получение облака по Id
      tags:
        - Clouds
      operationId: getCloudById
      parameters: 
        - name: cloud_id
          in: path
          required: True
          description: Индификатор заказа
          schema:
            type: string
          example: fdgd
      responses:
        "200":
          description: Успешный ответ заказа
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Clouds"  
        "default":
          description: other
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Error"
        
              
components:
  schemas:
    Cloud:
      type: object
      required:
        - OS
        - RAM
        - SSD
        - id_client
      properties:
        OS:
          type: string
          enum:
            - Winsows
            - Linux
        RAM:
          type: string
          example: 256
          description: в мб
        CPU:
          type: string
          example: 8
        id_client:
          type: string
          example: sdgfg
    Error:
      type: object
      required:
        - error_code
        - error_message
      properties:
        code:
          type: integer
        message:
          type: string
    Clouds:
      type: array
      items:
        $ref: "#/components/schemas/Cloud"
          
